const axios = require('axios');
const fs = require('fs');
const Genius = require('genius-lyrics-api');

// Remplacez 'YOUR_GENIUS_ACCESS_TOKEN' par votre token d'accès Genius (obtenu après inscription sur leur site)
const geniusAccessToken = 'u-gtlC4mUsPwFh040HX6Oby4xffGWOS6Fi80USGnTsnVxuorIFeVj_us0-gg5RO5';

// Liste de tous les chanteurs français
const artists = [
  'Adel Kachermi',
  'Ahmed Mouici',
  'Alain Barriere',
  'Alain Bashung',
  'Alain Chamfort',
  'Alain Lanty',
  'Alain Souchon',
  'Allain Leprest',
  'Amaury Vassili',
  'Amir',
  'Andre Bellec',
  'Andre Bezu',
  'Antoine',
  'Arnaud Fleurent Didier',
  'Arthur H',
  'Axel Bauer',
  'Baptiste Charden',
  'Ben L Oncle Soul',
  'Benabar',
  'Benjamin Biolay',
  'Benjamin Siksou',
  'Benoit Poher',
  'Bernard Haillant',
  'Bernard Lavilliers',
  'Bernard Minet',
  'Bernard Sauvat',
  'Bernie Bonvoisin',
  'Bertrand Cantat',
  'Bezu',
  'Bilal Hassani',
  'Bill Deraime',
  'Billy Bridge',
  'Boby Lapointe',
  'Brice Conrad',
  'Bruno Guillain',
  'Bruno Pelletier',
  'C Jerome',
  'Cali',
  'Calogero',
  'Carlos',
  'Charlelie Couture',
  'Charles Aznavour',
  'Charles Dumont',
  'Charles Trenet',
  'Christian Decamps',
  'Christian Delagrange',
  'Christian Dingler',
  'Christophe',
  'Christophe Mae',
  'Christophe Willem',
  'Claude Barzotti',
  'Claude Francois',
  'Claude Nougaro',
  'Claudio Capeo',
  'Colonel Reyel',
  'Cyril Cinelu',
  'Damien Sargue',
  'Daniel Balavoine',
  'Daniel Darc',
  'Daniel Guichard',
  'Daniel Lavoie',
  'Daniel Levi',
  'Dany Brillant',
  'Danyel Gerard',
  'Daran',
  'David Alexandre Winter',
  'David Hallyday',
  'David Marouani',
  'Dick Rivers',
  'Didier Barbelivien',
  'Didier Sustrac',
  'Didier Wampas',
  'Dominic Sonic',
  'Dominique A',
  'Doudou Masta',
  'Dranem',
  'Eddie Barclay',
  'Eddy Mitchell',
  'Edouard Algayon',
  'Emile Wandelmer',
  'Emmanuel Moire',
  'Enrico Macias',
  'Eric Charden',
  'Eric Morena',
  'Eric Virgal',
  'Etienne Daho',
  'Fabien Biancalani',
  'Fabien Fasake',
  'Fabien Incardona',
  'Faudel',
  'Felix Gray',
  'Felix Mayol',
  'Fernand Sardou',
  'Filip Nikolic',
  'Florent Mothe',
  'Florent Pagny',
  'Florian Rossi',
  'Francis Cabrel',
  'Francis Lalanne',
  'Franck Black',
  'Francky Vincent',
  'Francois Beranger',
  'Francois Corbier',
  'Francois Deguelt',
  'Francois Delsarte',
  'Francois Feldman',
  'Francois Soubeyran',
  'Francois Valery',
  'Frank Alamo',
  'Frank Delay',
  'Fred Blondin',
  'Frederic Francois',
  'Frederic Lerner',
  'Frederic Longbois',
  'Freeze Corleone',
  'Gael Faure',
  'Gaetan Roussel',
  'Gary Fico',
  'Georges Alain Jones',
  'Georges Bellec',
  'Georges Brassens',
  'Georges Chelon',
  'Georges Milton',
  'Georges Moustaki',
  'Georgius',
  'Gerald De Palmas',
  'Gerard Blanc',
  'Gerard Blanchard',
  'Gerard Lenorman',
  'Gerard Palaprat',
  'Gerard Sabbat',
  'Gilbert Becaud',
  'Gilbert Laffaille',
  'Gilbert Montagne',
  'Gilles Dreu',
  'Gilles Elbaz',
  'Gilles Servat',
  'Grand Corps Malade',
  'Gregoire',
  'Gregory Ken',
  'Gregory Lemarchal',
  'Guy Beart',
  'Guy Mardel',
  'Helmut Fritz',
  'Henri Des',
  'Henri Medus',
  'Henri Salvador',
  'Henri Tachan',
  'Henry Padovani',
  'Herbert Leonard',
  'Herve Cristiani',
  'Herve Vilard',
  'Hippocampe Fou',
  'Houcine',
  'Hubert Felix Thiefaine',
  'Hubert Lancelot',
  'Hugo Tsr',
  'Hugues Aufray',
  'Jack Lantier',
  'Jacob Desvarieux',
  'Jacques Debronckart',
  'Jacques Douai',
  'Jacques Dutronc',
  'Jacques Higelin',
  'Jazzy Bazz',
  'Jean Claude Darnal',
  'Jean Ferrat',
  'Jean Francois Bernardini',
  'Jean Francois Michael',
  'Jean Guidoni',
  'Jean Jacques Goldman',
  'Jean Jacques Lafon',
  'Jean Louis Aubert',
  'Jean Louis Constantin',
  'Jean Louis Murat',
  'Jean Luc Lahaye',
  'Jean Michel Caradec',
  'Jean Patrick Capdevielle',
  'Jean Pierre Francois',
  'Jean Pierre Mader',
  'Jean Pierre Savelli',
  'Jean Sablon',
  'Jeremy Chatelain',
  'Jeremy Frerot',
  'Jesse Garon',
  'Joe Dassin',
  'John William',
  'Johnny Hallyday',
  'Jok Air',
  'Jonathan Bermudes',
  'Jonathan Cerrada',
  'Jordy',
  'Jose Feliciano',
  'Julien Clerc',
  'Julien Dassin',
  'Julien Dore',
  'Julien Loko',
  'Karim Kacel',
  'Keen V',
  'Kendji Girac',
  'Kent',
  'Koba Lad',
  'Laurent Ban',
  'Laurent Voulzy',
  'Leni Escudero',
  'Leo Ferre',
  'Leo Rispal',
  'Lilian Renaud',
  'Louis Aubert',
  'Louis Bertignac',
  'Louis Chedid',
  'Lucky Blondo',
  'Luis Mariano',
  'Luis Miguel',
  'Lukas Delcourt',
  'M Pokora',
  'Mac Tyer',
  'Mano Solo',
  'Manu Chao',
  'Marc Lavoine',
  'Marcel Amont',
  'Marcel Merkes',
  'Marcel Mouloudji',
  'Marco Prince',
  'Mario Altery',
  'Mario Ramsamy',
  'Martial Tricoche',
  'Mathias Malzieu',
  'Mathieu Boogaerts',
  'Matt Pokora',
  'Matthieu Chedid',
  'Maurice Chevalier',
  'Maurice Fanon',
  'Maxime Le Forestier',
  'Maximilien Philippe',
  'MC Solaar',
  'Medhy Custos',
  'Merwan Rim',
  'Michel Berger',
  'Michel Delpech',
  'Michel Fugain',
  'Michel Jonasz',
  'Michel Orso',
  'Michel Paje',
  'Michel Polnareff',
  'Michel Sardou',
  'Mickael Miro',
  'Miossec',
  'Moha La Squale',
  'Moustique',
  'Nicola Sirkis',
  'Nicolas Peyrac',
  'Nino Ferrer',
  'Olivier Despax',
  'Pascal Danel',
  'Pascal Obispo',
  'Pascal Of Bollywood',
  'Pascal Sevran',
  'Patrice Maktav',
  'Patrick Abrial',
  'Patrick Bruel',
  'Patrick Fiori',
  'Patrick Hernandez',
  'Patrick Juvet',
  'Patrick Saint Eloi',
  'Patrick Topaloff',
  'Patxi Garat',
  'Paul Tourenne',
  'Paulus',
  'Phil Barney',
  'Philippe Chatel',
  'Philippe Clay',
  'Philippe Katerine',
  'Philippe Lavil',
  'Philippe Leotard',
  'Pierre Bachelet',
  'Pierre Bouvier',
  'Pierre Malar',
  'Pierre Perret',
  'Pierrick Lilliu',
  'Pit Baccardi',
  'Quentin Elias',
  'Quentin Mosimann',
  'Rachid Bahri',
  'Raphael',
  'Reda Caire',
  'Renan Luce',
  'Renaud',
  'Renaud Hantson',
  'Ricet Barrier',
  'Richard Anthony',
  'Richard Dewitte',
  'Richard Gotainer',
  'Rico Barbes',
  'Ringo',
  'Romain Cabon',
  'Romain Didier',
  'Sacha Distel',
  'Saint Granier',
  'Salvatore Adamo',
  'Sanseverino',
  'Sebastien El Chato',
  'Sebastien Izambard',
  'Sebastien Tellier',
  'Serge Gainsbourg',
  'Serge Lama',
  'Serge Reggiani',
  'Seth Gueko',
  'Sinclair',
  'Soan',
  'Soko',
  'Solal',
  'Stanislas',
  'Steeve Estatof',
  'Stephan Rizon',
  'Tete',
  'Thierry Amiel',
  'Thierry Hazard',
  'Thierry Pastor',
  'Thomas Dutronc',
  'Thomas Fersen',
  'Thomas Mars',
  'Tino Rossi',
  'Tizy Bone',
  'Tom Novembre',
  'Tonton David',
  'Vianney',
  'Vigon',
  'Vincent Delerm',
  'Vincent Niclo',
  'William Sheller',
  'X Man',
  'Xavier Depraz',
  'Yann Tiersen',
  'Ycare',
  'Yves Duteil',
  'Yves Jamait'
];

// Fonction pour récupérer les paroles d'une chanson depuis Genius
async function getLyrics(songTitle, artistName) {
  const options = {
    apiKey: geniusAccessToken,
    title: songTitle,
    artist: artistName,
    optimizeQuery: true
  };

  try {
    const lyrics = await Genius.getLyrics(options);
    return lyrics;
  } catch (error) {
    throw new Error(`Impossible de récupérer les paroles de "${songTitle}".`);
  }
}

// Fonction principale pour récupérer toutes les paroles et les enregistrer dans all.txt
async function fetchAndSaveAllLyrics() {
  const allLyrics = [];

  for (const artist of artists) {
    const songTitle = 'Nom de la chanson'; // Remplacez par le nom d'une chanson populaire de l'artiste
    try {
      const lyrics = await getLyrics(songTitle, artist);
      allLyrics.push(`${lyrics}\n`);
    } catch (error) {
      console.error(error.message);
    }
  }

  fs.writeFile('songs.txt', allLyrics.join('\n'), (err) => {
    if (err) {
      console.error('Erreur lors de l\'enregistrement des paroles dans all.txt');
    } else {
      console.log('Toutes les paroles ont été enregistrées dans all.txt');
    }
  });
}

// Appel de la fonction principale
fetchAndSaveAllLyrics();
